<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Journal Voucher {{ $journal->reference }}</title>
    
    <!-- Using Bootstrap CSS for layout consistency in View mode -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <style>
        body { background-color: #f8f9fa; padding: 20px; }
        .paper {
            background: white;
            max-width: 210mm;
            margin: 0 auto;
            padding: 10mm;
            box-shadow: 0 0 15px rgba(0,0,0,0.05);
            border-radius: 4px;
        }
        .table-custom th { background-color: #f8f9fa; text-transform: uppercase; font-size: 0.8rem; letter-spacing: 0.5px; }
        .stamp {
            position: absolute; top: 20px; right: 20px;
            font-size: 2rem; font-weight: bold; opacity: 0.2;
            transform: rotate(-15deg); border: 3px solid currentColor; padding: 5px 15px;
        }
        .stamp.draft { color: gray; }
        .stamp.review { color: orange; }
        .stamp.approved { color: blue; }
        .stamp.posted { color: green; }
        .stamp.voided { color: red; }
        
        @media print {
            body { background: white; padding: 0; }
            .paper { box-shadow: none; max-width: 100%; width: 100%; }
            .no-print { display: none !important; }
        }
    </style>
</head>
<body>

    <!-- Toolbar -->
    <div class="container mb-4 no-print d-flex justify-content-between align-items-center">
        <a href="{{ route('journals.index') }}" class="btn btn-outline-secondary btn-sm">&larr; Back to List</a>
        <div>
            @if($journal->status === 'draft')
                <form action="{{ route('journals.submit', $journal->id) }}" method="POST" class="d-inline">
                    @csrf <button class="btn btn-primary btn-sm">Submit for Review</button>
                </form>
            @elseif($journal->status === 'review')
                <form action="{{ route('journals.approve', $journal->id) }}" method="POST" class="d-inline">
                    @csrf <button class="btn btn-success btn-sm">Approve</button>
                </form>
            @elseif($journal->status === 'approved')
                <form action="{{ route('journals.post', $journal->id) }}" method="POST" class="d-inline">
                    @csrf <button class="btn btn-success btn-sm">Approve & Post</button>
                </form>
            @endif
            <button onclick="window.print()" class="btn btn-dark btn-sm ms-2"><i class="bi bi-printer"></i> Print</button>
        </div>
    </div>

    <!-- The Document -->
    <div class="paper position-relative">
        <div class="stamp {{ $journal->status }}">{{ strtoupper($journal->status) }}</div>

        <!-- Header -->
        <div class="row mb-5">
            <div class="col-6">
                <h4 class="fw-bold">{{ auth()->user()->tenant->company_name ?? 'Company Name' }}</h4>
                <div class="text-muted small">
                    Journal Entry<br>
                    Generated by SyneriaBooks
                </div>
            </div>
            <div class="col-6 text-end">
                <h3 class="fw-bold mb-3">JOURNAL #{{ $journal->reference ?? 'DRAFT' }}</h3>
                <table class="table table-borderless table-sm w-auto ms-auto text-end">
                    <tr><td class="text-muted">Date:</td><td class="fw-bold">{{ $journal->date->format('d M Y') }}</td></tr>
                    @if($journal->auto_reverse_date)
                        <tr><td class="text-muted">Reverses On:</td><td class="fw-bold">{{ $journal->auto_reverse_date->format('d M Y') }}</td></tr>
                    @endif
                    <tr><td class="text-muted">Amounts:</td><td>{{ ucfirst(str_replace('_', ' ', $journal->tax_type)) }}</td></tr>
                </table>
            </div>
        </div>

        <!-- Narration -->
        <div class="mb-4">
            <h6 class="text-uppercase text-muted small fw-bold">Narration</h6>
            <p class="border p-2 bg-light rounded">{{ $journal->description }}</p>
        </div>

        <!-- Lines -->
        <table class="table table-custom table-striped mb-4">
            <thead>
                <tr>
                    <th>Account</th>
                    <th>Details</th>
                    <th class="text-end">Debit</th>
                    <th class="text-end">Credit</th>
                    {{-- Only show Tax column if taxes were involved --}}
                    @if($journal->tax_type !== 'no_tax') <th class="text-end">Tax Amt</th> @endif
                </tr>
            </thead>
            <tbody>
                @foreach($journal->lines as $line)
                <tr>
                    <td>
                        <div class="fw-bold">{{ $line->account->code }}</div>
                        <div class="small text-muted">{{ $line->account->name }}</div>
                    </td>
                    <td>{{ $line->description }}</td>
                    <td class="text-end">{{ $line->debit > 0 ? number_format($line->debit, 2) : '-' }}</td>
                    <td class="text-end">{{ $line->credit > 0 ? number_format($line->credit, 2) : '-' }}</td>
                    @if($journal->tax_type !== 'no_tax')
                        <td class="text-end text-muted small">{{ number_format($line->tax_amount, 2) }}</td>
                    @endif
                </tr>
                @endforeach
            </tbody>
            <tfoot>
                <tr class="border-top-2 border-dark">
                    <td colspan="2" class="text-end fw-bold">Subtotal</td>
                    {{-- Logic to approximate subtotal for display since we store gross/net differently based on tax type --}}
                    @php
                        $totalTax = $journal->lines->sum('tax_amount');
                        $totalDebit = $journal->total_debit;
                        $totalCredit = $journal->total_credit;
                        // Simplification for display: 
                        $subtotalDebit = ($journal->tax_type == 'inclusive') ? $totalDebit - $totalTax : $totalDebit;
                        $subtotalCredit = ($journal->tax_type == 'inclusive') ? $totalCredit - $totalTax : $totalCredit;
                    @endphp
                    <td class="text-end fw-bold">{{ number_format($subtotalDebit, 2) }}</td>
                    <td class="text-end fw-bold">{{ number_format($subtotalCredit, 2) }}</td>
                    @if($journal->tax_type !== 'no_tax') <td></td> @endif
                </tr>
                @if($journal->tax_type !== 'no_tax')
                <tr>
                    <td colspan="2" class="text-end text-muted">Tax Total</td>
                    <td colspan="2" class="text-end text-muted">{{ number_format($totalTax, 2) }}</td>
                    <td></td>
                </tr>
                @endif
                <tr class="fs-5">
                    <td colspan="2" class="text-end fw-bold">Grand Total</td>
                    {{-- Note: In standard accounting, Debits and Credits match, so Grand Total is the balanced amount --}}
                    <td class="text-end fw-bold">{{ number_format($totalDebit, 2) }}</td>
                    <td class="text-end fw-bold">{{ number_format($totalCredit, 2) }}</td>
                    @if($journal->tax_type !== 'no_tax') <td></td> @endif
                </tr>
            </tfoot>
        </table>

        <hr class="my-5">

        <!-- History & Audit Trail (The Requested History Section) -->
        <div class="mt-5 no-print">
            <h5 class="fw-bold border-bottom pb-2">History & Activity Log</h5>
            <div class="list-group list-group-flush">
                @forelse($journal->activities as $activity)
                    <div class="list-group-item d-flex justify-content-between align-items-center px-0">
                        <div>
                            <span class="badge bg-secondary me-2">{{ strtoupper($activity->action) }}</span>
                            <span class="fw-bold">{{ $activity->user->name ?? 'System' }}</span>
                            <span class="text-muted ms-1">{{ $activity->description }}</span>
                        </div>
                        <small class="text-muted">{{ $activity->created_at->format('M d, Y h:i A') }}</small>
                    </div>
                @empty
                    <div class="text-muted fst-italic py-2">No activity recorded.</div>
                @endforelse
            </div>
        </div>

    </div>
</body>
</html>